"""v0

Revision ID: 6dec050e6d00
Revises: 
Create Date: 2025-06-26 12:47:43.502104

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '6dec050e6d00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###